apiVersion: v1
kind: Pod
metadata:
  name: ghost
  labels: 
    name: ghost
spec:
  restartPolicy: Always
  containers: 
    - image: "husseingalal/ghost"
      name: "ghost"
      ports:
      - containerPort: 2368
      env:
      - name: GHOST_USER
        value: ghost_user
      - name: GHOST_PASSWORD
        value: ghost_pass
      - name: GHOST_DB
        value: ghost
      volumeMounts:
        - name: ghost-vol
          mountPath: /var/lib/ghost
  volumes:
    - name: ghost-vol
      hostPath:
        path: /var/lib/ghost
